// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WagmiConfigProvider from "@/context/WagmiProvider";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} antialiased h-screen`}
      >
        <WagmiConfigProvider>
          {/* <div className=""></div> */}
          <Header />
          {children}
        </WagmiConfigProvider>
        <Toaster />
      </body>
    </html>
  );
}
